### ISSUE TITLE
SyntaxError: Unexpected token { (line:3)

### ISSUE THREAD

**Issue by nodecentral** [okhiroyuki/node-red-contrib-ip#14]
Hi

Just installed this plugin on my node-red instance and can see the following error in the pallet view.

**node-red-contrib-ip
1.0.0
SyntaxError: Unexpected token { (line:3)**

**Comment by okhiroyuki** [comment]
@nodecentral 
I have tried the installation again and have not seen any errors.

**Comment by nodecentral** [comment]
Ok, good to know, sadly not for me..
![EA78D4EE-1CC8-4D79-BED8-45CAAF6137BF](https://user-images.githubusercontent.com/4349292/77232585-d1aa7900-6b99-11ea-9d5e-3b6f7ee43296.jpeg)

**Comment by okhiroyuki** [comment]
@nodecentral 
There is no such error in my environment.

* Mac 10.15.3
* Node.js@10
* node-red@1.0.4

In addition, since unnecessary files were included, .npmignore was added so as not to be included.

**Comment by nodecentral** [comment]
Hi @okhiroyuki 

Is there a command I can run to tell me my node-js and NR versions?

FYI - I run my Node-RED instance in a Docker container, so not sure of the Linux/kernel version.

**Comment by andrei4002** [comment]
had the same issue, i was using a `node-red-docker:v8` container which isn't maintained anymore from what i see, the new node red for docker is here: https://hub.docker.com/r/nodered/node-red - using this container seems to fix the issue

**Comment by okhiroyuki** [comment]
@nodecentral 

> had the same issue, i was using a `node-red-docker:v8` container which isn't maintained anymore from what i see, the new node red for docker is here: https://hub.docker.com/r/nodered/node-red - using this container seems to fix the issue

Please check.
