### ISSUE TITLE
Public IP address

### ISSUE THREAD

**Issue by Paul-Reed** [okhiroyuki/node-red-contrib-ip#6]
My ISP regularly changes my public IP address, so I've written a flow that will update Cloudflare DNS settings with my current public IP address. Currently I use https://www.ipify.org/ to get my IP, but thought that this node would be a better solution.
However, reading the notes;
```
By default, for determining a public IP address, it queries the DNS records of OpenDNS
```
So does this node return the actual public address, or the public address as recorded by OpenDNS (which may be incorrect if my ISP has changed my IP)?

**Comment by okhiroyuki** [comment]
This node uses the [public-ip](https://github.com/sindresorhus/public-ip) library.

> In Node.js, it queries the DNS records of OpenDNS, Google DNS, and HTTPS services to determine your IP address. In browsers, it uses the excellent icanhaz and ipify services through HTTPS.

the default is to obtain from OpenDNS, OpenDNS, Google DNS, HTTPS services.

**Comment by Paul-Reed** [comment]
But if the local server has a different IP to the DNS provider (because the ISP has changed the IP) and is therefore disconnected, how will the node determine the true IP address of the local server?

**Comment by okhiroyuki** [comment]
In that case, HTTPS services may be applicable.

It seems that the new public-ip library can optionally be used only for HTTPS services.

> Use a HTTPS check using the icanhazip.com service instead of the DNS query. ipify.org is used as a fallback if icanhazip.com fails. This check is much more secure and tamper-proof, but also a lot slower. This option is only available in the Node.js version. The default behaviour is to check aginst DNS before using HTTPS fallback. If set to true, it will only check against HTTPS.

**Comment by Paul-Reed** [comment]
I'll do some more testing to make sure it's suitable for my user case.
Thank you for replying.
